# This file is required to bind ports in development,
# since binding ports in regular compose file will ruin scaling
# in production. Due to how `ports` directive is merged with two files.
#
# This file is ignored in production, but
# it is automatically picked up in development with:
#
#  $ docker compose up

services:
  web:
    ports:
      # We only bind ports directly in development:
      - "8080:8000"
    volumes:
      # We only mount source code in development:
      - .:/code
    build:
      # Needed for fixing permissions of files created by Docker
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN:-}
    command:
      - http
      - web:8000
      - --log=stdout
    depends_on:
      - web
    profiles:
      - ngrok
