JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
}

JAZZMIN_SETTINGS = {
    "hide_apps": ("token_blacklist", "authtoken", "django_celery_beat"),
    "site_title": "Novabiom",
    "site_header": "Novabiom",
    "site_brand": "Novabiom",
    "show_ui_builder": False,
    "search_model": [
        "user_app.User",
        "test_app.Test",
    ],
    "navigation_expanded": True,
    "topmenu_links": [
        {"name": "amoCRM", "url": "https://payamonovabiomru.amocrm.ru/dashboard"},
    ],
    "user_avatar": "profile_image",
    "order_with_respect_to": [
        "user_app",
        "user_app.User",
        "agents_app",
        "test_app",
        "test_app.Test",
        "supplements",
        "menu_app",
        "questionnaire",
        "questionnaire.QuestionnaireTemplate",
        "questionnaire.SectionTemplate",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "admin.LogEntry": "fas fa-user-clock",
        "rest_framework_api_key.APIKey": "fas fa-key",
        "user_app": "fas fa-users-cog",
        "user_app.User": "fas fa-user",
        "user_app.Email": "fas fa-envelope",
        "user_app.OneTimePassword": "fas fa-key",
        "user_app.Organisation": "fas fa-building",
        "agents_app.Agent": "fas fa-user-tie",
        "agents_app.AgentClient": "fas fa-user-friends",
        "agents_app.AgentSale": "fas fa-handshake",
        "agents_app.CashOutRequest": "fas fa-money-check-alt",
        "test_app.Test": "fas fa-vial",
        "test_app.Partner": "fas fa-hospital",
        "metrics.Metric": "fas fa-chart-line",
        "consultations_app.Consultation": "fas fa-hospital-user",
        "consultations_app.TimeTable": "fas fa-calendar",
        "supplements.Compound": "fas fa-pills",
        "supplements.Supplement": "fas fa-prescription-bottle",
        "supplements.SupplementBatch": "fas fa-box",
        "menu_app.Recipe": "fas fa-pizza-slice",
        "menu_app.Review": "fas fa-star",
        "info_app.FAQ": "fas fa-question",
        "info_app.Tag": "fas fa-tags",
        "info_app.Article": "fas fa-newspaper",
        "product_app.Product": "fas fa-shopping-basket",
        "product_app.Order": "fas fa-shopping-cart",
        "product_app.PromoCode": "fas fa-percent",
        "payments.LandingPayments": "fas fa-credit-card",
        "questionnaire.QuestionnaireTemplate": "fas fa-align-justify",
        "questionnaire.SectionTemplate": "fas fa-indent",
        "questionnaire.QuestionTemplate": "fas fa-question",
        "questionnaire.UserAnswer": "fas fa-user-edit",
        "questionnaire.SectionUserPassing": "fas fa-user-check",
    },
}
