JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": True,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-outline-info",
        "warning": "btn-outline-warning",
        "danger": "btn-outline-danger",
        "success": "btn-outline-success",
    },
}

JAZZMIN_SETTINGS = {
    "hide_apps": ("token_blacklist", "authtoken", "django_celery_beat"),
    "site_title": "Novabiom",
    "site_header": "Novabiom",
    "site_brand": "Novabiom",
    "show_ui_builder": False,
    "search_model": [
    ],
    "navigation_expanded": True,
    "topmenu_links": [
    ],
    "user_avatar": "profile_image",
    "order_with_respect_to": [
        "game",
        "game.SituationModel",
        "game.AgeGroupModel",
        "game.CityModel",
        "game.HintModel",
        "game.JobSphereModel",
        "game.ProductModel",
        "game.ReviewModel",
        "game.SpriteModel",
    ],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.Group": "fas fa-users",
        "game.AgeGroupModel": "fas fa-person",
        "game.CityModel": "fas fa-city",
        "game.HintModel": "fas fa-lightbulb",
        "game.JobSphereModel": "fas fa-screwdriver-wrench",
        "game.ProductModel": "fas fa-basket-shopping",
        "game.ReviewModel": "fas fa-comments",
        "game.SituationModel": "fas fa-comment-dots",
        "game.SpriteModel": "fas fa-person-half-dress",
    },
}
