# Generated by Django 5.2.6 on 2025-09-30 14:34

import django.db.models.deletion
from django.db import migrations, models


def populate_names(apps, schema_editor):
    FirstNameModel = apps.get_model("game", "FirstNameModel")
    LastNameModel = apps.get_model("game", "LastNameModel")

    # Создаем FirstName "ChangeMe" для всех гендеров
    FirstNameModel.objects.create(content="ChangeMe", gender="male")
    FirstNameModel.objects.create(content="ChangeMe", gender="female")

    # Создаем LastName "ChangeMe" для всех гендеров
    LastNameModel.objects.create(content="ChangeMe", gender="male")
    LastNameModel.objects.create(content="ChangeMe", gender="female")


def reverse_populate_names(apps, schema_editor):
    FirstNameModel = apps.get_model("game", "FirstNameModel")
    LastNameModel = apps.get_model("game", "LastNameModel")

    # Удаляем созданные записи при откате миграции
    FirstNameModel.objects.filter(content="ChangeMe").delete()
    LastNameModel.objects.filter(content="ChangeMe").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirstNameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(verbose_name="название")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Мужской"), ("female", "Женский")],
                        max_length=8,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LastNameModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(verbose_name="название")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Мужской"), ("female", "Женский")],
                        max_length=8,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="productrecommendationconditionmodel",
            name="age_group_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.agegroupmodel",
            ),
        ),
        migrations.AlterField(
            model_name="productrecommendationconditionmodel",
            name="children_condition",
            field=models.BooleanField(
                blank=True,
                choices=[(None, "Не важно"), (True, "Есть"), (False, "Нет")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="productrecommendationconditionmodel",
            name="city_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.citymodel",
            ),
        ),
        migrations.AlterField(
            model_name="productrecommendationconditionmodel",
            name="job_sphere_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.jobspheremodel",
            ),
        ),
        migrations.AlterField(
            model_name="productrecommendationconditionmodel",
            name="real_estate_condition",
            field=models.BooleanField(
                blank=True,
                choices=[(None, "Не важно"), (True, "Есть"), (False, "Нет")],
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="reviewmodel",
            name="is_product_in_answer",
            field=models.BooleanField(
                blank=True,
                choices=[
                    (True, "Не нужен, но указали"),
                    (False, "Нужен, но не указали"),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="reviewmodel",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="game.productmodel",
            ),
        ),
        migrations.AlterField(
            model_name="situationmodel",
            name="real_estate_condition",
            field=models.BooleanField(
                blank=True,
                choices=[(None, "Не важно"), (True, "Есть"), (False, "Нет")],
                null=True,
            ),
        ),
        # Добавляем операцию для заполнения данных
        migrations.RunPython(populate_names, reverse_populate_names),
    ]
