# Generated by Django 5.2.6 on 2025-09-30 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_firstnamemodel_lastnamemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationmodel',
            name='client_first_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='game.firstnamemodel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='generationmodel',
            name='client_last_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='game.lastnamemodel'),
            preserve_default=False,
        ),
    ]
