# Generated by Django 5.2.6 on 2025-10-01 20:37

from django.db import migrations, models


def set_all_age_groups_to_situation_models(apps, schema_editor):
    SituationModel = apps.get_model("game", "SituationModel")
    AgeGroupModel = apps.get_model("game", "AgeGroupModel")

    # Получаем все ситуации и все возрастные группы
    situations = SituationModel.objects.all()
    all_age_groups = AgeGroupModel.objects.all()

    # Для каждой ситуации добавляем все возрастные группы
    for situation in situations:
        situation.allowed_age_groups.add(*all_age_groups)


def unset_all_age_groups_to_situation_models(apps, schema_editor):
    SituationModel = apps.get_model("game", "SituationModel")

    # Для каждой ситуации удаляем все возрастные группы
    for situation in SituationModel.objects.all():
        situation.allowed_age_groups.clear()


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_generationmodel_client_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="situationmodel",
            name="allowed_age_groups",
            field=models.ManyToManyField(to="game.agegroupmodel"),
        ),
        migrations.RunPython(
            set_all_age_groups_to_situation_models,
            unset_all_age_groups_to_situation_models,
        ),
    ]
